### ISSUE TITLE
Hermes v0.18.0 compatibility: connect(is_reconnect) + sessions.json crash

### ISSUE THREAD

**Issue by kh-mitya** [pingram-io/hermes-gateway#1]
## Environment
- Hermes Agent v0.18.0 (2026.7.1)
- Pingram plugin v1.0.0 (commit 5914b88)
- Linux (Hetzner, Python 3.11)

## Bug 1: `connect()` missing `is_reconnect` parameter

Hermes v0.18.0 calls `adapter.connect(is_reconnect=bool)` but the adapter only accepts `self`:

```
✗ pingram-sms error: PingramSmsAdapter.connect() got an unexpected keyword argument 'is_reconnect'
```

**Fix** (`pingram_gateway/sms/adapter.py`):
```diff
-    async def connect(self) -> bool:
+    async def connect(self, is_reconnect: bool = False) -> bool:
```

## Bug 2: `sessions.json` non-dict entries crash `_legacy_session_entries()`

Hermes `sessions.json` can contain non-dict values (e.g. `"_README": "..."`). The plugin iterates over all values assuming they are dicts:

```
AttributeError: 'str' object has no attribute 'get'
  File "pingram_gateway/core/directory.py", line 98, in _legacy_session_entries
    origin = session.get("origin") or {}
             ^^^^^^^^^^^
```

**Fix** (`pingram_gateway/core/directory.py`):
```diff
     for session in data.values():
+        if not isinstance(session, dict):
+            continue
         origin = session.get("origin") or {}
```

---

Both fixes tested and working on Hermes v0.18.0 — gateway now connects successfully.

**Comment by millerm30** [comment]
Both of these are in https://github.com/pingram-io/hermes-gateway/pull/2 (plugin 1.0.1):

1. `connect(self, *, is_reconnect: bool = False)` on email, SMS, and voice adapters
2. `_legacy_session_entries()` skips `_README` / non-dict `sessions.json` values
